name: deployment
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build_job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: test
              run: echo Hello, world!
