name: deployment
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build_job:
        runs-on: self-hosted
        steps:
            # - uses: actions/checkout@v3
            - name: stop docker container
              run: docker stop weather
            - name: remove docker container
              run: docker rm -f weather
            - name: pull changes
              run: cd && cd weather && git pull
            - name: build project
              run: cd && cd weather && docker build -t weather .
            - name: run docker container
              run: docker run --restart=always -d --name weather -p 8080:8080 weather
