name: linting, testing, building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: cd client && npm install
            - name: unit testing
              if: always()
              run: cd client && npm run test
    deploy:
        runs-on: self-hosted
        steps:
            # - uses: actions/checkout@v3
            - name: stop docker container
              run: docker stop weather
            - name: remove docker container
              run: docker rm -f weather
            - name: pull changes
              run: cd && cd weather && git pull
            - name: build project
              run: cd && cd weather && docker build -t weather .
            - name: run docker container
              run: docker run --restart=always -d --name weather -p 8080:8080 weather
